# Generated by Django 3.2 on 2021-10-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0002_auto_20210527_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Временное окно',
                'verbose_name_plural': 'Временные окна',
            },
        ),
        migrations.AddField(
            model_name='quest',
            name='photo',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('text',), name='unique text'),
        ),
        migrations.AddField(
            model_name='order',
            name='timeslot',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='q.timeslot'),
        ),
        migrations.AddField(
            model_name='quest',
            name='timeslot_list',
            field=models.ManyToManyField(to='q.TimeSlot'),
        ),
    ]
