# Generated by Django 3.2 on 2021-12-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0003_auto_20211026_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='price',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
